# Autogenerated file
def render(header, form):
    yield """
"""
    if form.get('success'):
        yield """<div class=\"row text-center row justify-content-md-center\">
    <div class=\"alert alert-success floating-alert alert-dismissible fade show text-center\" timeout=\"2000\" role=\"alert\">
      <span><i class=\"bi bi-check-circle-fill\"></i> """
        yield str(form.get('success'))
        yield """
      <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\" aria-label=\"Close\"></button></span>
    </div>
</div>
"""
    yield """

<form id=\""""
    yield str(form['name'])
    yield """\" name=\""""
    yield str(form['name'])
    yield """\" action=\"\" method=\"post\" class=\"needs-validation row justify-content-md-center\" novalidate>
<div class=\"col-md-12\">
        <h2 class=\"text-center\">"""
    yield str(header)
    yield """</h2>
</div>
    <div class=\"row col-md-9\">
"""
    for field in form.get('fields'):
        yield """
"""
        if field.get("prepend_class"):
            yield """<div class=\"position-relative """
            yield str(field.get("prepend_class"))
            yield """ mt-3\"></div>"""
        if field.get("type") == "checkbox":
            yield """
                <div class=\""""
            yield str(field.get("css"))
            yield """ position-relative mt-3\">
                    <div class=\"form-check form-switch\">
                      <input class=\"form-check-input """
            yield str(field.get("checkbox_css"))
            yield """\" type=\"checkbox\" name=\""""
            yield str(field.get("name"))
            yield """\" """
            if field.get("value") == "on":
                yield """checked """
            yield """id=\""""
            yield str(field.get("name"))
            yield """\">
                      <label class=\"form-check-label\" for=\""""
            yield str(field.get("name"))
            yield """\"><small>"""
            yield str(field.get("label"))
            yield """</small></label>
                    </div>
                </div>
"""
        elif field.get("type") == "hr":
            yield """            <div class=\""""
            yield str(field.get("css"))
            yield """ position-relative mt-2 text-center div-line\">
                   <hr class=\"hr-line \">
                   <span class=\"text-line fw-bold fs-6\">"""
            yield str(field.get("value"))
            yield """</span>
            </div>
"""
        else:
            yield """            <div class=\""""
            yield str(field.get("css"))
            yield """ position-relative mt-3\">
                <label for=\""""
            yield str(field.get("name"))
            yield """\" class=\"form-label\"><small>"""
            yield str(field.get("label"))
            yield """</small></label>
                <div class=\"input-group\">
                    <input type=\""""
            yield str(field.get("type"))
            yield """\" class=\"form-control"""
            if field.get("value") != "":
                yield """ """
                yield str(field.get("valid_css"))
            yield """\"
                            id=\""""
            yield str(field.get("name"))
            yield """\" name=\""""
            yield str(field.get("name"))
            yield """\"
                            value=\""""
            yield str(field.get("value"))
            yield """\"
                            aria-describedby=\""""
            yield str(field.get("name"))
            yield """_feedback\" required>
                    <div class=\"invalid-tooltip\">
                      """
            yield str(field.get("label"))
            yield """ """
            yield str(field.get("error"))
            yield """ 
                    </div>
"""
            if field.get("show_password"):
                yield """                    <button type=\"button\" class=\"btn btn-outline-secondary toggle-password\">
                        <i class=\"bi bi-eye-slash\"></i>
                    </button>
"""
            yield """
               </div>
              </div>
"""
        if field.get("extend_class"):
            yield """<div class=\"position-relative """
            yield str(field.get("extend_class"))
            yield """ mt-3\"></div>"""
    yield """</div>
    <div class=\"row mt-3\">
    
        <div class=\"col-md-4 position-relative text-center\">
        </div>

        <div class=\"col-md d-grid gap-2 col-md\">
          <button class=\"btn btn-primary\" name=\"submit\" type=\"submit\">Submit</button>

        </div>
        <div class=\"col-md-4 position-relative text-center\">
        </div>
    </div>

</form>

"""
    if form.get('disable_id'):
        yield """
<!--  JavaScript to disable all input fields 
<script>
    // Call the function to toggle fields
    toggleFormFields('"""
        yield str(form.get('disable_id'))
        yield """', '"""
        yield str(form.get('name'))
        yield """');
</script>
-->
"""
