# Autogenerated file
def render(page, application, session, form):
    # Autogenerated file
    def render1(*a, **d):
        yield """<!doctype html>
<html lang=\"en\">
  <head>
    <meta charset=\"utf-8\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">
    <title>"""
        yield str(page)
        yield """</title>
    <link href=\"/static/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN\" crossorigin=\"anonymous\">
    <link rel=\"stylesheet\" href=\"/static/local.css\">
  </head>
  <body>
    <nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">
      <div class=\"container\">
        <a class=\"navbar-brand\" href=\"/\">"""
        yield str(application.application_name)
        yield """</a>
        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">
          <span class=\"navbar-toggler-icon\"></span>
        </button>
 
     """
        if page != "Login":
            yield """
        <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">

          <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">
            <li class=\"nav-item dropdown\">
              <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">
                Configuration
              </a>
              <ul class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">
              
                """
            for item in application.factory._list:
                yield """                <li><a class=\"dropdown-item\" href=\"/config/"""
                yield str(item.item_name)
                yield """\">"""
                yield str(item.item_name)
                yield """</a></li>
                """
            yield """                
                <li><a class=\"dropdown-item\" href=\"/settings/network\">Network</a></li>
                <li><a class=\"dropdown-item\" href=\"#\">Another action</a></li>
                <li><hr class=\"dropdown-divider\"></li>
                <li><a class=\"dropdown-item\" href=\"#\">Something else here</a></li>
              </ul>            
          </ul>
          
            <ul class=\"navbar-nav\">
                <li class=\"nav-item dropdown\">
                    <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">
                        <img src=\"/static/account.png\" alt=\"Account\">
                    </a>
                    <ul class=\"dropdown-menu dropdown-menu-end\" aria-labelledby=\"navbarDropdown\">
                        <li><a class=\"dropdown-item\" href=\"/user/settings\">Account Settings</a></li>
                        <li><hr class=\"dropdown-divider\"></li>
                        <li><a class=\"dropdown-item\" href=\"/user/logout\">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </div>
        """
        yield """
      </div>
    </nav>

    <div class=\"container my-5\">
"""
    yield from render1()
    yield """
    <div class=\"col alert alert-danger w-50 alert-dismissible fade show floating-alert\" align=\"center\">
        <strong>Important!</strong> This is a floating alert.
        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\" aria-label=\"Close\"></button>
    </div>

    <!-- Floating Alert -->

<form action=\"\" method=\"post\" class=\"needs-validation\" novalidate>
    <div class=\"row pb-3\">
        <div class=\"col col-sm-3\">
            &nbsp;
        </div>
        <div class=\"col col-sm-6\">
            <h2>"""
    yield str(page)
    yield """</h2>
        </div>
    </div>
    """
    for field in form:
        yield """
        <div class=\"row pb-3\">
            """
        if field.get("type") == "checkbox":
            yield """                <div class=\"col col-sm-3\">
                    &nbsp;
                </div>
                <div class=\"col col-sm-6\">
                
                    <div class=\"form-check form-switch\">
                      <input class=\"form-check-input\" type=\"checkbox\" name=\""""
            yield str(field.get("name"))
            yield """\" """
            if field.get("value") == "on":
                yield """checked """
            yield """id=\""""
            yield str(field.get("name"))
            yield """\">
                      <label class=\"form-check-label\" for=\""""
            yield str(field.get("name"))
            yield """\">"""
            yield str(field.get("label"))
            yield """</label>
                    </div>
                </div>

            """
        else:
            yield """
                <div class=\"col col-sm-3\">
                    <label class=\"control-label d-flex justify-content-end align-items-end pe-3\">"""
            yield str(field.get("label"))
            yield """</label>
                </div>
                
                <div class=\"col col-sm-6\">
                    <input type=\""""
            yield str(field.get("type"))
            yield """\" class=\"form-control"""
            if not field.get("valid") and field.get("required"):
                yield """ is-invalid"""
            yield """\" id=\""""
            yield str(field.get("name"))
            yield """\" 
                    name=\""""
            yield str(field.get("name"))
            yield """\" placeholder=\"\" value=\""""
            yield str(field.get("value"))
            yield """\" """
            if field.get("required"):
                yield """required"""
            yield """>

                    <div class=\"col-sm-4 invalid-feedback\">
                    <small>"""
            yield str(field["error"])
            yield """</small>
                    </div>
                </div>
            """
        yield """        </div>


    """
    yield """    <div class=\"row pb-3\">
        <div class=\"col col-sm-3\">
            &nbsp:            
        </div>
        <div class=\"col col-sm-3\">
            <button class=\"w-100 btn btn-primary btn-lg\" type=\"submit\">Submit</button>
        </div>
    </form>

"""
# Autogenerated file
    def render2(*a, **d):
        yield """    </div>

    <script src=\"/static/bootstrap.bundle.min.js\" integrity=\"sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL\" crossorigin=\"anonymous\"></script>

<!-- <script src=\"local.js\"></script> -->
        <script src=\"/static/local.js\"></script>

  </body>
</html>
"""
    yield from render2()
