# Autogenerated file
def render(page, application, factory, session):
    yield """
<script defer src=\"/static/sse.js\"></script>

"""
# Autogenerated file
    def render1(*a, **d):
        yield """<!doctype html>
<html lang=\"en\">
  <head>
    <meta charset=\"utf-8\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">
    <title>"""
        yield str(page)
        yield """</title>
    <link href=\"/static/bootstrap.min.css\" rel=\"stylesheet\">
    <link href=\"/static/bootstrap-icons.min.css\" rel=\"stylesheet\">

    <link rel=\"stylesheet\" href=\"/static/local.css\">

      <script defer src=\"/static/bootstrap.bundle.min.js\"></script>


  <!-- <script src=\"local.js\"></script> -->
     <script defer src=\"/static/local.js\"></script>
     

  </head>
  <body>
    <nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">
      <div class=\"container\">
        <a class=\"navbar-brand\" href=\"/\">"""
        yield str(application.application_name)
        yield """</a>
        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">
          <span class=\"navbar-toggler-icon\"></span>
        </button>
 
     """
        if page != "Login":
            yield """
        <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">

          <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">
            <li class=\"nav-item dropdown\">
              <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">
                Configuration
              </a>
              <ul class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">
              
                """
            for item in factory._list:
                yield """                <li><a class=\"dropdown-item\" href=\"/config/"""
                yield str(item.item_name)
                yield """\">"""
                yield str(item.item_name)
                yield """</a></li>
                """
            yield """                
                <li><a class=\"dropdown-item\" href=\"/settings/network\">Network</a></li>
                <li><a class=\"dropdown-item\" href=\"#\">Another action</a></li>
                <li><hr class=\"dropdown-divider\"></li>
                <li><a class=\"dropdown-item\" href=\"#\">Something else here</a></li>
              </ul>            
          </ul>
          
            <ul class=\"navbar-nav\">
                <li class=\"nav-item dropdown\">
                    <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">
                        <img src=\"/static/account.png\" alt=\"Account\">
                    </a>
                    <ul class=\"dropdown-menu dropdown-menu-end\" aria-labelledby=\"navbarDropdown\">
                        <li><a class=\"dropdown-item\" href=\"/user/settings\">Account Settings</a></li>
                        <li><hr class=\"dropdown-divider\"></li>
                        <li><a class=\"dropdown-item\" href=\"/user/logout\">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </div>
        """
        yield """
      </div>
    </nav>

    <div class=\"container my-5\">
"""
    yield from render1()
    yield """
    <div class=\"container mt-5\">
        <h1 class=\"text-center\">SSE Messages</h1>
        <div class=\"card\">
            <div class=\"card-header\">
                Server-Sent Events
            </div>
            <div class=\"card-body\">
                <div id=\"messages\" class=\"mb-3 border rounded p-3\" style=\"height: 200px; overflow-y: auto; background-color: #f8f9fa;\">
                    <p class=\"text-muted\">Messages will appear here...</p>
                </div>
                <div class=\"d-flex\">
                    <button id=\"startButton\" class=\"btn btn-success me-2\">Start Listening</button>
                    <button id=\"stopButton\" class=\"btn btn-danger me-2\" disabled>Stop Listening</button>
                </div>
            </div>
        </div>
    </div>


"""
# Autogenerated file
    def render2(*a, **d):
        yield """    </div>

  </body>
</html>
"""
    yield from render2()
