# Autogenerated file
def render(page, application, session, factory, form):
    # Autogenerated file
    def render1(*a, **d):
        yield """<!doctype html>
<html lang=\"en\">
  <head>
    <meta charset=\"utf-8\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">
    <title>"""
        yield str(page)
        yield """</title>
    <link href=\"/static/bootstrap.min.css\" rel=\"stylesheet\">
    <link href=\"/static/bootstrap-icons.min.css\" rel=\"stylesheet\">

    <link rel=\"stylesheet\" href=\"/static/local.css\">

      <script defer src=\"/static/bootstrap.bundle.min.js\"></script>


  <!-- <script src=\"local.js\"></script> -->
     <script defer src=\"/static/local.js\"></script>

  </head>
  <body>
    <nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">
      <div class=\"container\">
        <a class=\"navbar-brand\" href=\"/\">"""
        yield str(application.application_name)
        yield """</a>
        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">
          <span class=\"navbar-toggler-icon\"></span>
        </button>
 
     """
        if page != "Login":
            yield """
        <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">

          <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">
            <li class=\"nav-item dropdown\">
              <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">
                Configuration
              </a>
              <ul class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">
              
                """
            for item in factory._list:
                yield """                <li><a class=\"dropdown-item\" href=\"/config/"""
                yield str(item.item_name)
                yield """\">"""
                yield str(item.item_name)
                yield """</a></li>
                """
            yield """                
                <li><a class=\"dropdown-item\" href=\"/settings/network\">Network</a></li>
                <li><a class=\"dropdown-item\" href=\"#\">Another action</a></li>
                <li><hr class=\"dropdown-divider\"></li>
                <li><a class=\"dropdown-item\" href=\"#\">Something else here</a></li>
              </ul>            
          </ul>
          
            <ul class=\"navbar-nav\">
                <li class=\"nav-item dropdown\">
                    <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">
                        <img src=\"/static/account.png\" alt=\"Account\">
                    </a>
                    <ul class=\"dropdown-menu dropdown-menu-end\" aria-labelledby=\"navbarDropdown\">
                        <li><a class=\"dropdown-item\" href=\"/user/settings\">Account Settings</a></li>
                        <li><hr class=\"dropdown-divider\"></li>
                        <li><a class=\"dropdown-item\" href=\"/user/logout\">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </div>
        """
        yield """
      </div>
    </nav>

    <div class=\"container my-5\">
"""
    yield from render1()
    yield """


<div class=\"col\">

    <form name=\"form\" class=\"needs-validation\" novalidate action=\"\" method=\"post\">

        <div class=\"row g-3 justify-content-md-center\">
          <div class=\"col-md-3 p-1 text-center h3\">
          Login to """
    yield str(application.application_name)
    yield """
          </div>
        </div>
        <div class=\"row g-3 justify-content-md-center\">
          <div class=\"col-md-3 p-1\">
              <input type=\"username\" id=\"username\" placeholder=\"username\" name=\"username\" value=\""""
    yield str(form.get("username"))
    yield """\" class=\"form-control """
    if not form["valid"]:
        yield """is-invalid"""
    yield """\" required/>
          </div>
        </div>
        <div class=\"row g-3 justify-content-md-center\">
          <div class=\"col-md-3 p-1\">
              <input type=\"password\" id=\"password\" placeholder=\"password\" name=\"password\" class=\"form-control """
    if not form.get("valid"):
        yield """is-invalid"""
    yield """\" required/>
              <div class=\"invalid-feedback\">
                Username or password unknown.
              </div>
          </div>
        </div>
        <div class=\"row g-3 justify-content-md-center\">
            <div class=\"col-md-3 p-1 d-grid gap-2\">
                <button class=\"btn btn-primary\" type=\"submit\">Login</button>
            </div>
        </div>
        
     
    </form>

</div>

<script>
// Example starter JavaScript for disabling form submissions if there are invalid fields
(() => """
    yield """{
  'use strict'

  // Fetch all the forms we want to apply custom Bootstrap validation styles to
  const forms = document.querySelectorAll('.needs-validation')

  // Loop over them and prevent submission
  Array.from(forms).forEach(form => """
    yield """{
    form.addEventListener('submit', event => """
    yield """{
      if (!form.checkValidity()) """
    yield """{
        event.preventDefault()
        event.stopPropagation()
      }

      form.classList.add('was-validated')
    }, false)
  })
})()
</script>

"""
# Autogenerated file
    def render2(*a, **d):
        yield """    </div>

  </body>
</html>
"""
    yield from render2()
