# Autogenerated file
def render(page, application, form_fields):
    # Autogenerated file
    def render1(*a, **d):
        yield """<!doctype html>
<html lang=\"en\">
  <head>
    <meta charset=\"utf-8\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">
    <title>Bootstrap demo</title>
    <link href=\"/static/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN\" crossorigin=\"anonymous\">
    <!-- <link rel=\"stylesheet\" href=\"styles.css\"> -->
  </head>
  <body>
    <nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">
      <div class=\"container\">
        <a class=\"navbar-brand\" href=\"#\">"""
        yield str(application['application_name'])
        yield """</a>
        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">
          <span class=\"navbar-toggler-icon\"></span>
        </button>
 
        <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">
          <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">
            <li class=\"nav-item\">
              <a class=\"nav-link active\" aria-current=\"page\" href=\"/\">Home</a>
            </li>
            <li class=\"nav-item dropdown\">
              <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">
                Configuration
              </a>
              <ul class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">
                <li><a class=\"dropdown-item\" href=\"/settings/network\">Network</a></li>
                <li><a class=\"dropdown-item\" href=\"#\">Another action</a></li>
                <li><hr class=\"dropdown-divider\"></li>
                <li><a class=\"dropdown-item\" href=\"#\">Something else here</a></li>
              </ul>
            </li>
            <li class=\"nav-item\">
              <a class=\"nav-link disabled\">Disabled</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class=\"container my-5\">
"""
    yield from render1()
    yield """
<h2>"""
    yield str(page)
    yield """</h2>


        """
# Autogenerated file
    def render2(*a, **d):
        yield """  <div class=\"col-md-7 col-lg-8\">
    <h4 class=\"mb-3\">Wifi credentials</h4>
    <form name=\"form\" class=\"needs-validation\" novalidate action=\"/settings/network\" method=\"post\">
    
      <div class=\"row g-3\">
      """
        for field in form_fields:
            yield """
        <div class=\""""
            yield str(field["columns"])
            yield """\">
          <label for=\""""
            yield str(field["name"])
            yield """\" class=\"form-label\">"""
            yield str(field["text"])
            yield """</label>
          <input type=\""""
            yield str(field["type"])
            yield """\" class=\"form-control"""
            if field["error"]:
                yield """  is-invalid"""
            yield """\" id=\""""
            yield str(field["name"])
            yield """\" name=\""""
            yield str(field["name"])
            yield """\" placeholder=\"\" value=\""""
            yield str(field["value"])
            yield """\" required>
          <div class=\"invalid-feedback\">
            """
            yield str(field["error_txt"])
            yield """
          </div>
        </div>

      """
        yield """      
      <button class=\"w-100 btn btn-primary btn-lg\" type=\"submit\">Submit</button>
      </form>
      </div>

<script>
// Example starter JavaScript for disabling form submissions if there are invalid fields
(() => """
        yield """{
  'use strict'

  // Fetch all the forms we want to apply custom Bootstrap validation styles to
  const forms = document.querySelectorAll('.needs-validation')

  // Loop over them and prevent submission
  Array.from(forms).forEach(form => """
        yield """{
    form.addEventListener('submit', event => """
        yield """{
      if (!form.checkValidity()) """
        yield """{
        event.preventDefault()
        event.stopPropagation()
      }

      form.classList.add('was-validated')
    }, false)
  })
})()
</script>
"""
    yield from render2()
    yield """

"""
# Autogenerated file
    def render3(*a, **d):
        yield """    </div>

    <script src=\"/static/bootstrap.bundle.min.js\" integrity=\"sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL\" crossorigin=\"anonymous\"></script>
    <!-- <script src=\"main.js\"></script> -->
  
  </body>
</html>
"""
    yield from render3()
    yield """

"""
